! Remember to update this value if you add more 2D arrays.
   integer, parameter :: n2d_fields=33
!
#ifdef USE_BREAKS
   integer  break_mask(E2DFIELD)
   integer  break_stat(E2DFIELD)
#endif
   REALTYPE,dimension(E2DFIELD),target :: t_zo,t_z,t_Dlast,t_D,DU,DV
   REALTYPE U(E2DFIELD)
   REALTYPE V(E2DFIELD)
   REALTYPE UEx(E2DFIELD)
   REALTYPE VEx(E2DFIELD)
   REALTYPE fU(E2DFIELD)
   REALTYPE fV(E2DFIELD)
   REALTYPE ru(E2DFIELD)
   REALTYPE rv(E2DFIELD)
   REALTYPE Uint(E2DFIELD)
   REALTYPE Vint(E2DFIELD)
   REALTYPE Uinto(E2DFIELD)
   REALTYPE Vinto(E2DFIELD)
   REALTYPE res_du(E2DFIELD)
   REALTYPE res_u(E2DFIELD)
   REALTYPE res_dv(E2DFIELD)
   REALTYPE res_v(E2DFIELD)
!kbk
   REALTYPE ruu(E2DFIELD)
   REALTYPE rvv(E2DFIELD)
!kbk
   REALTYPE SlUx(E2DFIELD)
   REALTYPE SlVx(E2DFIELD)
   REALTYPE Slru(E2DFIELD)
   REALTYPE Slrv(E2DFIELD)
   REALTYPE zub(E2DFIELD)
   REALTYPE zvb(E2DFIELD)
   REALTYPE zub0(E2DFIELD)
   REALTYPE zvb0(E2DFIELD)
   REALTYPE An(E2DFIELD)
   REALTYPE AnX(E2DFIELD)
   REALTYPE fwf(E2DFIELD)
   REALTYPE fwf_int(E2DFIELD)
   REALTYPE EWbdy(jmax),ENbdy(imax),EEbdy(jmax),ESbdy(imax)

