   REALTYPE Am_2d(E2DFIELD)
   REALTYPE AmX_2d(E2DFIELD)
#ifndef NO_3D
   REALTYPE :: Am_3d(I3DFIELD)
   REALTYPE :: AmX_3d(I3DFIELD)
   REALTYPE :: AmU_3d(I3DFIELD)
   REALTYPE :: AmV_3d(I3DFIELD)
#endif
